const GET_INIT_ITEMS = "GET_INIT_ITEMS";
const INPUT_VALUE_CHANGE = "INPUT_VALUE_CHANGE";
const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const TOGGLE_ITEM = "TOGGLE_ITEM";

export {
  GET_INIT_ITEMS,
  INPUT_VALUE_CHANGE,
  ADD_ITEM,
  DELETE_ITEM,
  TOGGLE_ITEM
};
