const GET_INIT_ITEMS = "GET_INIT_ITEMS";
const GET_INIT_DATA = "GET_INIT_DATA";
const INPUT_VALUE_CHANGE = "INPUT_VALUE_CHANGE";
const ADD_ITEM_START = "ADD_ITEM_START";
const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const DELETE_ITEM_START = "DELETE_ITEM_START";
const TOGGLE_ITEM_START = "TOGGLE_ITEM_START";
const TOGGLE_ITEM = "TOGGLE_ITEM";

export {
  GET_INIT_ITEMS,
  GET_INIT_DATA,
  INPUT_VALUE_CHANGE,
  ADD_ITEM,
  ADD_ITEM_START,
  DELETE_ITEM,
  DELETE_ITEM_START,
  TOGGLE_ITEM_START,
  TOGGLE_ITEM
};
